development:
  adapter: postgresql
  encoding: unicode
  database: AmazonDeliveryLocator
  pool: 5
  username: ashugupt
  password: ashugupt

test:
  adapter: postgresql
  encoding: unicode
  database: AmazonDeliveryLocatorTest
  pool: 5
  username: ashugupt
  password: ashugupt